# Hosts.yml
ungrouped:
  hosts:
    managedhost-app-1:
      ansible_host: 0.0.0.0
      ansible_connection: ssh
      ansible_port: 2223
      ansible_user: root
      ansible_ssh_private_key_file: ./secrets/id_rsa
    managedhost-app-2:
      ansible_host: 0.0.0.0
      ansible_connection: ssh
      ansible_port: 2224
      ansible_user: root
      ansible_ssh_private_key_file: ./secrets/id_rsa
    managedhost-app-3:
      ansible_host: 0.0.0.0
      ansible_connection: ssh
      ansible_port: 2225
      ansible_user: root
      ansible_ssh_private_key_file: ./secrets/id_rsa
    


app_group:
  hosts:
    managedhost-app-1:
    managedhost-app-2:
    managedhost-app-3:

# loadbalancer:
#   hosts:
#     loadbalancer-nginx:
#       ansible_host: localhost
#       ansible_connection: local

loadbalancer:
  hosts:
    localhost:
      ansible_connection: local